---
sudo: required
cache:
  node: true
  tidy: true
  directories:
    - vendor/bundle
    - node_modules
    - $HOME/.nvm
addons:
  chrome: stable
before_script:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn
language: ruby
rvm:
  - 2.6.4
script:
  - bundle exec rspec
before_install: gem install bundler -v 2.0.1
