markdown : rdiscount
encoding: utf-8
permalink : /:year/:month/:day/:title.html
rdiscount extensions : [smart]
title: Mike Rogers
description: The occasional ramblings on programming and technology.
rss_path: /rss.xml
cdn_uri: ''
#cdn_uri: https://mikerogers.io

name: Mike Rogers
highlighter: true

production_url : https://mikerogers.io

env: production

exclude:
  - "bower_components"
  - "bower.json"
    
sass:
    syntax: scss        # scss|sass
    style:  compressed  # nested|expanded|compact|compressed

gems:
  - octopress-autoprefixer

jekyll-press:
  exclude: ['sitemap.txt', 'robots.txt'] # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
